### ISSUE TITLE
Updating the ReadMe

### ISSUE THREAD

**Issue by strypey** [TheAssassin/fetcher#1]
I was going to update the ReadMe, then realized it was a bit more complicated than I thought. There are a lot of instructions and links that are very specific to the Etcher project, for example the Debian repo info.

> Add Etcher debian repository:
echo "deb https://dl.bintray.com/resin-io/debian stable etcher" | sudo tee /etc/apt/sources.list.d/etcher.l

Can we set up a Debian repo like this? Is it worth it at this point?

**Comment by TheAssassin** [comment]
> Can we set up a Debian repo like this?

We could, probably, but it's a lot of work to maintain a Debian repository. Also, it comes with some security issues, one needs to ensure nobody but the maintainers have access. Otherwise, attackers might upload insecure Linux kernels or programs with backdoors, which a Linux system using the repository will accept without any further checks.

> Is it worth it at this point?

Being an AppImage developer, I think a Debian repository is way harder to use for the average user. With an AppImage, you just download a single file, and you have the entire app. No sudo, nothing complex, it just works. Such AppImages are already available from the release page.

I would therefore just remove any Etcher specific parts from the README and add a link to the release page.

**Comment by strypey** [comment]
> I would therefore just remove any Etcher specific parts from the README 

Done

> add a link to the release page.

Link please?

**Comment by TheAssassin** [comment]
https://github.com/TheAssassin/better-etcher/releases

**Comment by strypey** [comment]
I've updated the ReadMe to reflect the final name: Fetcher. I'm going to go ahead and close this Issue, unless there's anything else about the ReadMe that needs fixing?
