### ISSUE TITLE
Rethinking this project

### ISSUE THREAD

**Issue by strypey** [TheAssassin/fetcher#5]
@TheAssassin:
> I developed the idea of creating a better image writer in a real programming language like C++ last year ... a tool for "engineers"

This kind of exists (c++ with QT4 for cross-platform GUI), although AFAIK it only makes boot USBs, not CDs/DVDs:
https://github.com/unetbootin/unetbootin

There are two reasons the Trisquel community doesn't like to recommend it. One is that most of the distros it offers to download from within the UI are not endorsed by the FSF. This is discussed here:
https://trisquel.info/en/forum/unetbootin-fork

A few years ago someone made a fork that included only [FSF-endorsed distros](https://www.gnu.org/distros/free-distros.html), but this doesn't appear to have been maintained. Maybe because this guy created a lot of extra work for himself, because every time a distro releases a new version the program needs to be updated to download that instead of the last version:
https://notabug.org/tomlukeywood/FreeNetBootin

A fork that only burns .ISOs already downloaded by the user (do one job well) would be great.

The other issue that used to come up in the Trisquel forums about uNetbootin is that it hasn't always done a great job of making boot USBs that work reliably for all distros. I haven't used it for a long time, since I learned how to use dd in a terminal. YMMV ;)

**Comment by TheAssassin** [comment]
unetbootin has a few big flaws. Let's ignore this download thing for a while, and consider the "arbitrary ISO file" part. unetbootin puts its own bootloader on the disks and that then loads the ISO. The difference to tools like etcher is that they just write the image as-is to a block device. That's possible since those ISOs and `.img`s are "hybrid" nowadays.

What you need is basically a graphical frontend to `dd` that shows some useful information you don't have on the commandline. There you can screw up really badly since you need to know the right `/dev/*` name etc., but that's something people hardly understand. Even power users like me find that annoying.

So in the end you need a fast, simple and responsive tool that writes raw images to a block device and shows the progress. It should allow for referring to block devices by some descriptive properties (size, label, ..., vendor, type) instead of the name of the device file. Perhaps you also have a sudo prompt to elevate permissions quickly.
I figured it can't be *that* hard to make that, perhaps one can use `dd` as a backend directly or something. There's also GNOME MultiWriter that does pretty much what its name says, but I don't like the UI very much and it's error prone.

etcher etc. also don't do any magic, they just write the ISO to the device. They just have o support multiple OSes, which makes things cumbersome and hard to test. We don't have to do that.

So, pro writing our own:

  - doesn't have to but can be made fancy at any time
  - can be written in C++, so it's quite fast
  - multi language support is easy to implement in Qt
  - I don't want to touch node JS code...

**Comment by strypey** [comment]
@TheAssassin:
> netbootin puts its own bootloader on the disks and that then loads the ISO.

Ah! That explains all the weird issues I found when I used to use it.
 
> What you need is basically a graphical frontend to `dd` that shows some useful information you don't have on the commandline.

Sounds good to me. Would that work for burning .ISOs to CDs/DVDs too?
This is becoming less relevant, as there are fewer and fewer working
devices that can't boot from USB. But for now, I think it's still good
to include it if we can.

> Perhaps you also have a sudo prompt to elevate permissions quickly.

Sure. Like GParted, you could just pop up a modal when the program
boots, with text explaining that the program needs admin permission to
do it's job, a field for entering it, and cancel/ ok buttons (or
similar). Or we could take more of an 'object capabilities' approach,
and include the explanation and admin password field above the 'go'
button, so admin permission is only granted to that etching process,
then withdrawn.

> GNOME MultiWriter

Seems to be aimed at making large numbers of boot USBs at once, so
probably over-engineered for our purposes.

>  They just have to support multiple OSes, which makes things cumbersome and hard to test. We don't have to do that.

For Trisquel purposes, I'd really like to be able to offer one graphical
tool that works the same on Windows or MacOS, as Etcher does, to help
people who are new to GNU/Linux. This helps people when they are
installing it for the first time, or they want to install to a Win/Mac
device they just got, and for some reason don't have a GNU/Linux device
available to make a boot USB (a friend of mine was in that exact
situation just recently).

I believe GNU dd is cross-platform (?) so if that is the back-end and QT
is the front-end, would it create a huge amount of extra work to make it
run on Windows and Mac? Would it work to bundle the relevant port of dd
within the AppImage?

Final thought: the best UX would be for the GNU/Linux .ISOs itself to
bundle a little cross-platform, GUI program that etches it to a USB and
makes it bootable.

**Comment by TheAssassin** [comment]
CD creation is something other tools can do much better. For all platforms there's excellent open source tools, e.g., K3b or InfraRecorder. I would focus only on writing to rewritable media, i.e., SD cards, USB flash drives, ... It's also easier to just write to block devices than to write to optical media. I just want to write a fast and handy tool with exactly one purpose: writing image files to disks, with some progress bar and maybe 

I'm not saying this tool can't work on other platforms, and it can be designed to have different implementations for the image writing for different platforms, but don't expect any support from me for non-Linux OSes. I'm a Linux user, not a Trisquel user or developer, and I personally need such a tool for Linux workstations, at least for the moment.
Also, I don't want to run anything proprietary on my computers (any more).
But I guess it shouldn't be too hard to find someone to write the relevant code for e.g., Windows or macOS. I even think the Linux-ish code should run on WSL.

I already experimented a bit with UDisks2, a daemon installed on most distributions already, which provides an abstract high-level view on what they call drives. You can get a list of all drives, filter "peripheral" (as in, non-optical, non-system removable devices, i.e., memory cards, flash drives, ...), get their vendors and model names and display a nice and most notably **understandable** list of plugged in drives. That way, I can quickly tell the software which of these I want to flash the image to. Unfortunately, you can't ship this service in an AppImage, you have to rely on it being there, and communicate with it through DBus.

> Final thought: the best UX would be for the GNU/Linux .ISOs itself to bundle a little cross-platform, GUI program that etches it to a USB and makes it bootable.

I disagree. Bundling tools always means to embed redundant tools in every image, also these can never be updated (otherwise you'd ruin the integrity, and also old files on people's computers won't ever be updated). This means you have a huge pile of support work to do, mostly telling people that you can't help them or they may have to still download a tool for the job. It's just a bad idea. It's very similar to an old approach we had at AppImage to embed desktop integration. The result was that we switched to telling people to install software for that job separately for the abovementioned reasons. After years, we still see people embed that script, though, although it's pretty broken and we explicitly state that this is wrong...

Let's follow the UNIX approach: make one tool for one purpose and make that tool do what it's supposed to do as good as possible. There's no need to overload tools with functionality, that's counterproductive.

**Comment by TheAssassin** [comment]
Actually, there's https://github.com/KDE/isoimagewriter, which from old screenshots looks pretty much like what I have in mind. I'll build it from the source code, and will see whether that'd be an option. Perhaps we could just extend that a bit.

Edit: it doesn't quite work; it didn't even build on Ubuntu 18.04, but I was able to downgrade a few dependencies. However, the built binary segfaulted. That's annoying.

**Comment by strypey** [comment]
> I just want to write a fast and handy tool with exactly one purpose: writing image files to disks, with some progress bar and maybe ...
> but don't expect any support from me for non-Linux OSes

Fair enough, but this is no longer a user-respecting replacement for Etcher, because it doesn't do most of what makes Etcher useful. The problem Etcher solves is helping new users create boot media to install GNU/Linux, especially if they don't (yet) have a GNU/Linux system available.

If you want a Linux-only tool for writing to block devices, why bother creating a new GUI app at all? Why not just use dd? Or contribute to improving GNOME MultiWriter?

> Let's follow the UNIX approach

This UNIX rule-of-thumb was coined before GUI programs existed. IMHO it only applies to back-end components, not GUI apps, which are almost by definition a way of combining multiple back-end components into a unified interface.

**Comment by TheAssassin** [comment]
> Fair enough, but this is no longer a user-respecting replacement for Etcher, because it doesn't do most of what makes Etcher useful. The problem Etcher solves is helping new users create boot media to install GNU/Linux, especially if they don't (yet) have a GNU/Linux system available.

I'm not saying this app can't support other OSes. But like with every open source software, there must be a maintainer for this stuff. I'm sure there will be a power user who might want to maintain this.

Actually, I've been playing with the KDE ISO image writer a bit recently. It needs some love here and there, but it's already cross-platform, it'd just need a better/simpler UI. Also it doesn't build on non-cutting-edge-KDE systems, which is something that needs to be fixed.

**Comment by strypey** [comment]
@TheAssassin:
> there must be a maintainer for this stuff.

Of course, you're not obliged to do anything that doesn't scratch your
itch ;) 

> I've been playing with the KDE ISO image writer a bit recently.

What's it called/ where can I read more about it?

**Comment by TheAssassin** [comment]
It's called KDE ISO Image Writer... https://www.omgubuntu.co.uk/2017/06/new-iso-image-writer-app-kde https://github.com/KDE/isoimagewriter

**Comment by TheAssassin** [comment]
Closing this project due to inactivity (lack of time). As an alternative, Pop OS's [Popsicle](https://github.com/pop-os/popsicle) application has proven to work well. It doesn't require any browser stuff, it's just a native Gtk+ application.
Trying to get them to create and ship AppImages, see https://github.com/pop-os/popsicle/issues/104.
